---
- name: "SCORED | 2.1.1 | PATCH | Ensure chargen services are not enabled | chargen-dgram,chargen-stream"
  block:
      - name: "SCORED | 2.1.1 | PATCH | Ensure chargen services are not enabled | chargen-dgram"
        stat:
            path: /etc/xinetd.d/chargen-dgram
        register: chargen_dgram_service

      - name: "SCORED | 2.1.1 | PATCH | Ensure chargen services are not enabled | chargen-dgram"
        service:
            name: chargen-dgram
            enabled: no
        notify: restart xinetd
        when:
            - chargen_dgram_service.stat.exists

      - name: "SCORED | 2.1.1 | PATCH | Ensure chargen services are not enabled | chargen-stream"
        stat:
            path: /etc/xinetd.d/chargen-stream
        register: chargen_stream_service

      - name: "SCORED | 2.1.1 | PATCH | Ensure chargen services are not enabled | chargen-stream"
        service:
            name: chargen-stream
            enabled: no
        notify: restart xinetd
        when:
            - chargen_stream_service.stat.exists
  when:
      - ubuntu1804cis_rule_2_1_1
  tags:
      - level1
      - scored
      - services
      - patch
      - rule_2.1.1
      - skip_ansible_lint

- name: "SCORED | 2.1.2 | PATCH | Ensure daytime services are not enabled | daytime-dgram,daytime-stream"
  block:
      - name: "SCORED | 2.1.2 | PATCH | Ensure daytime services are not enabled | daytime-dgram"
        stat:
            path: /etc/xinetd.d/daytime-dgram
        register: daytime_dgram_service

      - name: "SCORED | 2.1.2 | PATCH | Ensure daytime services are not enabled | daytime-dgram"
        service:
            name: daytime-dgram
            enabled: no
        notify: restart xinetd
        when:
            - daytime_dgram_service.stat.exists

      - name: "SCORED | 2.1.2 | PATCH | Ensure daytime services are not enabled | daytime-stream"
        stat:
            path: /etc/xinetd.d/daytime-stream
        register: daytime_stream_service

      - name: "SCORED | 2.1.2 | PATCH | Ensure daytime services are not enabled | daytime-stream"
        service:
            name: daytime-stream
            enabled: no
        notify: restart xinetd
        when:
            - daytime_stream_service.stat.exists
  when:
      - ubuntu1804cis_rule_2_1_2
  tags:
      - level1
      - scored
      - patch
      - rule_2.1.2
      - skip_ansible_lint

- name: "SCORED | 2.1.3 | PATCH | Ensure discard services are not enabled | discard-dgram,discard-stream"
  block:
      - name: "SCORED | 2.1.3 | PATCH | Ensure discard services are not enabled | discard-dgram"
        stat:
            path: /etc/xinetd.d/discard-dgram
        register: discard_dgram_service

      - name: "SCORED | 2.1.3 | PATCH | Ensure discard services are not enabled | discard-dgram"
        service:
            name: discard-dgram
            enabled: no
        notify: restart xinetd
        when:
            - discard_dgram_service.stat.exists

      - name: "SCORED | 2.1.3 | PATCH | Ensure discard services are not enabled | discard-stream"
        stat:
            path: /etc/xinetd.d/discard-stream
        register: discard_stream_service

      - name: "SCORED | 2.1.3 | PATCH | Ensure discard services are not enabled | discard-stream"
        service:
            name: discard-stream
            enabled: no
        notify: restart xinetd
        when:
            - discard_stream_service.stat.exists
  when:
      - ubuntu1804cis_rule_2_1_3
  tags:
      - level1
      - scored
      - patch
      - rule_2.1.3
      - skip_ansible_lint

- name: "SCORED | 2.1.4 | PATCH | Ensure echo services are not enabled | echo-dgram,echo-stream"
  block:
      - name: "SCORED | 2.1.4 | PATCH | Ensure echo services are not enabled | echo-dgram"
        stat:
            path: /etc/xinetd.d/echo-dgram
        register: echo_dgram_service

      - name: "SCORED | 2.1.4 | PATCH | Ensure echo services are not enabled | echo-dgram"
        service:
            name: echo-dgram
            enabled: no
        notify: restart xinetd
        when:
            - echo_dgram_service.stat.exists

      - name: "SCORED | 2.1.4 | PATCH | Ensure echo services are not enabled | echo-stream"
        stat:
            path: /etc/xinetd.d/echo-stream
        register: echo_stream_service

      - name: "SCORED | 2.1.4 | PATCH | Ensure echo services are not enabled | echo-stream"
        service:
            name: echo-stream
            enabled: no
        notify: restart xinetd
        when:
            - echo_stream_service.stat.exists
  when:
      - ubuntu1804cis_rule_2_1_4
  tags:
      - level1
      - scored
      - patch
      - rule_2.1.4
      - skip_ansible_lint

- name: "SCORED | 2.1.5 | PATCH | Ensure time services are not enabled | time-dgram,time-stream"
  block:
      - name: "SCORED | 2.1.5 | PATCH | Ensure time services are not enabled | time-dgram"
        stat:
            path: /etc/xinetd.d/time-dgram
        register: time_dgram_service

      - name: "SCORED | 2.1.5 | PATCH | Ensure time services are not enabled | time-dgram"
        service:
            name: time-dgram
            enabled: no
        notify: restart xinetd
        when:
            - time_dgram_service.stat.exists

      - name: "SCORED | 2.1.5 | PATCH | Ensure time services are not enabled | time-stream"
        stat:
            path: /etc/xinetd.d/time-stream
        register: time_stream_service

      - name: "SCORED | 2.1.5 | PATCH | Ensure time services are not enabled | time-stream"
        service:
            name: time-stream
            enabled: no
        notify: restart xinetd
        when:
            - time_stream_service.stat.exists
  when:
      - ubuntu1804cis_rule_2_1_5
  tags:
      - level1
      - scored
      - patch
      - rule_2.1.5
      - skip_ansible_lint

- name: "SCORED | 2.1.6 | PATCH | Ensure rsh server is not enabled | rsh, rlogin, rexec"
  block:
      - name: "SCORED | 2.1.6 | PATCH | Ensure rsh server is not enabled | rsh"
        service:
          name: rsh.socket
          state: stopped
          enabled: false
        when:
          - not ubuntu1804cis_rsh_server
          - rsh_service_status.stdout == "loaded"
          - ubuntu1804cis_rule_2_1_6

      - name: "SCORED | 2.1.6 | PATCH | Ensure rsh server is not enabled | rlogin"
        service:
          name: rlogin.socket
          state: stopped
          enabled: false
        when:
          - not ubuntu1804cis_rsh_server
          - rlogin_service_status.stdout == "loaded"
          - ubuntu1804cis_rule_2_1_6

      - name: "SCORED | 2.1.6 | PATCH | Ensure rsh server is not enabled | rexec"
        service:
          name: rexec.socket
          state: stopped
          enabled: false
        when:
          - not ubuntu1804cis_rsh_server
          - rexec_service_status.stdout == "loaded"
          - ubuntu1804cis_rule_2_1_6
  tags:
    - level1
    - scored
    - patch
    - rule_2.1.6

- name: "SCORED | 2.1.7 | PATCH | Ensure talk server is not enabled"
  service:
    name: ntalk
    state: stopped
    enabled: false
  when:
    - not ubuntu1804cis_ntalk_server
    - ntalk_service_status.stdout == "loaded"
    - ubuntu1804cis_rule_2_1_7
  tags:
    - level1
    - scored
    - patch
    - rule_2.1.7

- name: "SCORED | 2.1.8 | PATCH | Ensure telnet server is not enabled"
  service:
    name: telnet
    state: stopped
    enabled: false
  when:
    - not ubuntu1804cis_telnet_server
    - telnet_service_status.stdout == "loaded"
    - ubuntu1804cis_rule_2_1_8
  tags:
    - level1
    - scored
    - patch
    - rule_2.1.8

- name: "SCORED | 2.1.9 | PATCH | Ensure tftp server is not enabled"
  block:
      - name: "SCORED | 2.1.9 | PATCH | Ensure tftp server is not enabled"
        stat:
            path: /etc/xinetd.d/tftp
        register: tftp_service

      - name: "SCORED | 2.1.9 | PATCH | Ensure tftp server is not enabled"
        service:
            name: tftp
            state: stopped
            enabled: no
        notify: restart xinetd
        when:
            - tftp_service.stat.exists
            - not ubuntu1804cis_tftp_server
        tags:
            - skip_ansible_lint
  when:
      - ubuntu1804cis_rule_2_1_9
  tags:
      - level1
      - scored
      - patch
      - rule_2.1.9

- name: "SCORED | 2.1.10 | PATCH | Ensure xinetd is not enabled"
  service:
      name: xinetd
      state: stopped
      enabled: false
  when:
      - xinetd_service_status.stdout == "loaded"
      - not ubuntu1804cis_xinetd_required
      - ubuntu1804cis_rule_2_1_10
  tags:
      - level1
      - patch
      - scored
      - rule_2.1.10

- name: "SCORED | 2.1.11 | PATCH | Ensure openbsd-inetd is not installed"
  apt:
    name: openbsd-inetd
    state: absent
  when:
    - openbsd_inetd_service_status.stdout == "ok installed"
    - ubuntu1804cis_rule_2_1_11
  tags:
    - level1
    - patch
    - scored
    - rule_2.1.11

- name: "NOTSCORED | 2.2.1.1 | PATCH | Ensure time synchronization is in use"
  block:
      - name: "NOTSCORED | 2.2.1.1 | PATCH | Ensure time synchronization is in use - service install"
        apt:
            name: "{{ ubuntu1804cis_time_synchronization }}"
            state: present
            install_recommends: false

      - name: "NOTSCORED | 2.2.1.1 | PATCH | Ensure time synchronization is in use - service start"
        service:
            name: "{{ ubuntu1804cis_time_synchronization }}"
            state: started
            enabled: true

      - name: "NOTSCORED | 2.2.1.1 | PATCH | Ensure time synchronization is in use - service stop ntp"
        service:
            name: "{{ ntp_service[ansible_os_family] }}"
            state: stopped
            enabled: false
        when:
            - ubuntu1804cis_time_synchronization == "chrony"
            - ntpd_service_status.stdout == "loaded"

      - name: "NOTSCORED | 2.2.1.1 | PATCH | Ensure time synchronization is in use - service stop chrony"
        service:
            name: chronyd
            state: stopped
            enabled: false
        ignore_errors: true
        when:
            - ubuntu1804cis_time_synchronization == "ntp"
            - chronyd_service_status.stdout == "loaded"

  when:
      - ubuntu1804cis_rule_2_2_1_1
  tags:
      - level1
      - notscored
      - ntp
      - patch
      - rule_2.2.1.1

- name: "SCORED | 2.2.1.2 | PATCH | Ensure ntp is configured"
  block:
      - name: "SCORED | 2.2.1.2 | PATCH | Ensure ntp is configured | modify /etc/ntp.conf"
        template:
            src: ntp.conf.j2
            dest: /etc/ntp.conf
            owner: root
            group: root
            mode: 0644

      - name: "SCORED | 2.2.1.2 | PATCH | Ensure ntp is configured | modify /etc/init.d/ntp"
        lineinfile:
            dest: /etc/init.d/ntp
            regexp: "^RUNASUSER"
            line: "RUNASUSER=ntp"
  when:
      - ubuntu1804cis_time_synchronization == "ntp"
      - ubuntu1804cis_rule_2_2_1_2
  tags:
      - level1
      - scored
      - ntp
      - patch
      - rule_2.2.1.2

- name: "SCORED | 2.2.1.3 | PATCH | Ensure chrony is configured"
  template:
      src: chrony.conf.j2
      dest: "{{ chrony_config_file[ansible_os_family] }}"
      owner: root
      group: root
      mode: 0644
  when:
      - ubuntu1804cis_time_synchronization == "chrony"
      - ubuntu1804cis_rule_2_2_1_3
  tags:
      - level1
      - scored
      - ntp
      - chrony
      - patch
      - rule_2.2.1.3

- name: "SCORED | 2.2.1.3 | PATCH | Ensure chrony is configured | modify /etc/sysconfig/chronyd | 1"
  lineinfile:
      dest: /etc/sysconfig/chronyd
      regexp: "^(#)?OPTIONS"
      line: "OPTIONS=\"-u chrony\""
      state: present
      create: true
  when:
      - ubuntu1804cis_time_synchronization == "chrony"
      - ubuntu1804cis_rule_2_2_1_3
  tags:
      - level1
      - scored
      - ntp
      - chrony
      - patch
      - rule_2.2.1.3

- name: "SCORED | 2.2.2 | PATCH | Ensure X Window System is not installed"
  apt:
      name:
        - "@X Window System"
        - "x11*"
      state: absent
  when:
      - not ubuntu1804cis_xwindows_required
      - ubuntu1804cis_rule_2_2_2
  tags:
      - level1
      - scored
      - xwindows
      - patch
      - rule_2.2.2

- name: "SCORED | 2.2.3 | PATCH | Ensure Avahi Server is not enabled"
  service:
      name: avahi-daemon
      state: stopped
      enabled: false
  when:
      - not ubuntu1804cis_avahi_server
      - avahi_service_status.stdout == "loaded"
      - ubuntu1804cis_rule_2_2_3
  tags:
      - level1
      - scored
      - avahi
      - services
      - patch
      - rule_2.2.3

- name: "SCORED | 2.2.4 | PATCH | Ensure CUPS is not enabled"
  service:
      name: cups
      state: stopped
      enabled: false
  when:
      - not ubuntu1804cis_cups_server
      - cups_service_status.stdout == "loaded"
      - ubuntu1804cis_rule_2_2_4
  tags:
      - level1
      - scored
      - cups
      - services
      - patch
      - rule_2.2.4

- name: "SCORED | 2.2.5 | PATCH | Ensure DHCP Server is not enabled"
  service:
      name: dhcpd
      state: stopped
      enabled: false
  when:
      - not ubuntu1804cis_dhcp_server
      - dhcpd_service_status.stdout == "loaded"
      - ubuntu1804cis_rule_2_2_5
  tags:
      - level1
      - scored
      - dhcp
      - services
      - patch
      - rule_2.2.5

- name: "SCORED | 2.2.6 | PATCH | Ensure LDAP server is not enabled"
  service:
      name: slapd
      state: stopped
      enabled: false
  when:
      - not ubuntu1804cis_ldap_server
      - slapd_service_status.stdout == "loaded"
      - ubuntu1804cis_rule_2_2_6
  tags:
      - level1
      - scored
      - ldap
      - services
      - patch
      - rule_2.2.6

- name: "SCORED | 2.2.7 | PATCH | Ensure NFS and RPC are not enabled"
  service:
      name: nfs
      state: stopped
      enabled: false
  when:
      - not ubuntu1804cis_nfs_rpc_server
      - nfs_service_status.stdout == "loaded"
      - ubuntu1804cis_rule_2_2_7
  tags:
      - level1
      - scored
      - nfs
      - rpc
      - services
      - patch
      - rule_2.2.7

- name: "SCORED | 2.2.7 | PATCH | Ensure RPC is not enabled"
  service:
      name: rpcbind
      state: stopped
      enabled: false
  when:
      - not ubuntu1804cis_nfs_rpc_server
      - rpcbind_service_status.stdout == "loaded"
      - ubuntu1804cis_rule_2_2_7
  tags:
      - level1
      - scored
      - nfs
      - rpc
      - services
      - patch
      - rule_2.2.7

- name: "SCORED | 2.2.8 | PATCH | Ensure DNS Server is not enabled"
  service:
      name: named
      state: stopped
      enabled: false
  when:
      - not ubuntu1804cis_named_server
      - named_service_status.stdout == "loaded"
      - ubuntu1804cis_rule_2_2_8
  tags:
      - level1
      - scored
      - patch
      - rule_2.2.8

- name: "SCORED | 2.2.9 | PATCH | Ensure FTP Server is not enabled"
  service:
      name: vsftpd
      state: stopped
      enabled: false
  when:
      - not ubuntu1804cis_vsftpd_server
      - vsftpd_service_status.stdout == "loaded"
      - ubuntu1804cis_rule_2_2_9
  tags:
      - level1
      - scored
      - patch
      - rule_2.2.9

- name: "SCORED | 2.2.10 | PATCH | Ensure HTTP server is not enabled"
  service:
      name: httpd
      state: stopped
      enabled: false
  when:
      - not ubuntu1804cis_httpd_server
      - httpd_service_status.stdout == "loaded"
      - ubuntu1804cis_rule_2_2_10
  tags:
      - level1
      - scored
      - patch
      - rule_2.2.10

- name: "SCORED | 2.2.11 | PATCH | Ensure IMAP and POP3 server is not enabled"
  service:
      name: dovecot
      state: stopped
      enabled: false
  when:
      - not ubuntu1804cis_dovecot_server
      - dovecot_service_status.stdout == "loaded"
      - ubuntu1804cis_rule_2_2_11
  tags:
      - level1
      - scored
      - patch
      - rule_2.2.11

- name: "SCORED | 2.2.12 | PATCH | Ensure Samba is not enabled"
  service:
      name: smb
      state: stopped
      enabled: false
  when:
      - not ubuntu1804cis_smb_server
      - smb_service_status.stdout == "loaded"
      - ubuntu1804cis_rule_2_2_12
  tags:
      - level1
      - scored
      - patch
      - rule_2.2.12

- name: "SCORED | 2.2.13 | PATCH | Ensure HTTP Proxy Server is not enabled"
  service:
      name: squid
      state: stopped
      enabled: false
  when:
      - not ubuntu1804cis_squid_server
      - squid_service_status.stdout == "loaded"
      - ubuntu1804cis_rule_2_2_13
  tags:
      - level1
      - scored
      - patch
      - rule_2.2.13

- name: "SCORED | 2.2.14 | PATCH | Ensure SNMP Server is not enabled"
  service:
      name: snmpd
      state: stopped
      enabled: false
  when:
      - not ubuntu1804cis_snmp_server
      - snmpd_service_status.stdout == "loaded"
      - ubuntu1804cis_rule_2_2_14
  tags:
      - level1
      - scored
      - patch
      - rule_2.2.14

- name: "SCORED | 2.2.15 | PATCH | Ensure mail transfer agent is configured for local-only mode"
  lineinfile:
      dest: /etc/postfix/main.cf
      regexp: "^(#)?inet_interfaces"
      line: "inet_interfaces = localhost"
  when:
      - not ubuntu1804cis_is_mail_server
      - postfix_installed.rc == 0
      - ubuntu1804cis_rule_2_2_15
  tags:
      - level1
      - scored
      - patch
      - rule_2.2.15

- name: "SCORED | 2.2.16 | PATCH | Ensure rsync service is not enabled "
  service:
    name: rsync
    state: stopped
    enabled: false
  when:
    - not ubuntu1804cis_rsyncd_server
    - rsyncd_service_status.stdout == "loaded"
    - ubuntu1804cis_rule_2_2_16
  tags:
    - level1
    - scored
    - patch
    - rule_2.2.16

- name: "SCORED | 2.2.17 | PATCH | Ensure NIS Server is not enabled"
  service:
      name: ypserv
      state: stopped
      enabled: false
  when:
      - not ubuntu1804cis_nis_server
      - ypserv_service_status.stdout == "loaded"
      - ubuntu1804cis_rule_2_2_17
  tags:
      - level1
      - scored
      - patch
      - rule_2.2.17

- name: "SCORED | 2.3.1 | PATCH | Ensure NIS Client is not installed"
  apt:
      name: ypbind
      state: absent
  when:
      - not ubuntu1804cis_ypbind_required
      - ubuntu1804cis_rule_2_3_1
  tags:
      - level1
      - scored
      - patch
      - rule_2.3.1

- name: "SCORED | 2.3.2 | PATCH | Ensure rsh client is not installed"
  apt:
      name: rsh
      state: absent
  when:
      - not ubuntu1804cis_rsh_required
      - ubuntu1804cis_rule_2_3_2
  tags:
      - level1
      - scored
      - patch
      - rule_2.3.2

- name: "SCORED | 2.3.3 | PATCH | Ensure talk client is not installed"
  apt:
      name: talk
      state: absent
  when:
      - not ubuntu1804cis_talk_required
      - ubuntu1804cis_rule_2_3_3
  tags:
      - level1
      - scored
      - patch
      - rule_2.3.3

- name: "SCORED | 2.3.4 | PATCH | Ensure telnet client is not installed"
  apt:
      name: telnet
      state: absent
  when:
      - not ubuntu1804cis_telnet_required
      - ubuntu1804cis_rule_2_3_4
  tags:
      - level1
      - scored
      - patch
      - rule_2.3.4

- name: "SCORED | 2.3.5 | PATCH | Ensure LDAP client is not installed"
  apt:
      name: openldap-clients
      state: absent
  when:
      - not ubuntu1804cis_openldap_clients_required
      - ubuntu1804cis_rule_2_3_5
  tags:
      - level1
      - scored
      - patch
      - rule_2.3.5
