---
- name: "SCORED | 5.1.1 | PATCH | Ensure cron daemon is enabled"
  service:
      name: "{{ cron_service[ansible_os_family] }}"
      enabled: true
  when:
      - ubuntu1804cis_rule_5_1_1
  tags:
      - level1
      - scored
      - patch
      - cron
      - rule_5.1.1

- name: "SCORED | 5.1.2 | PATCH | Ensure permissions on /etc/crontab are configured"
  file:
      dest: /etc/crontab
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu1804cis_rule_5_1_2
  tags:
      - level1
      - scored
      - patch
      - cron
      - rule_5.1.2

- name: "SCORED | 5.1.3 | PATCH | Ensure permissions on /etc/cron.hourly are configured"
  file:
      dest: /etc/cron.hourly
      state: directory
      owner: root
      group: root
      mode: 0700
  when:
      - ubuntu1804cis_rule_5_1_3
  tags:
      - level1
      - scored
      - patch
      - cron
      - rule_5.1.3

- name: "SCORED | 5.1.4 | PATCH | Ensure permissions on /etc/cron.daily are configured"
  file:
      dest: /etc/cron.daily
      state: directory
      owner: root
      group: root
      mode: 0700
  when:
      - ubuntu1804cis_rule_5_1_4
  tags:
      - level1
      - scored
      - patch
      - cron
      - rule_5.1.4

- name: "SCORED | 5.1.5 | PATCH | Ensure permissions on /etc/cron.weekly are configured"
  file:
      dest: /etc/cron.weekly
      state: directory
      owner: root
      group: root
      mode: 0700
  when:
      - ubuntu1804cis_rule_5_1_5
  tags:
      - level1
      - scored
      - patch
      - cron
      - rule_5.1.5

- name: "SCORED | 5.1.6 | PATCH | Ensure permissions on /etc/cron.monthly are configured"
  file:
      dest: /etc/cron.monthly
      state: directory
      owner: root
      group: root
      mode: 0700
  when:
      - ubuntu1804cis_rule_5_1_6
  tags:
      - level1
      - scored
      - patch
      - cron
      - rule_5.1.6

- name: "SCORED | 5.1.7 | PATCH | Ensure permissions on /etc/cron.d are configured"
  file:
      dest: /etc/cron.d
      state: directory
      owner: root
      group: root
      mode: 0700
  when:
      - ubuntu1804cis_rule_5_1_7
  tags:
      - level1
      - scored
      - patch
      - cron
      - rule_5.1.7

- name: "SCORED | 5.1.8 | PATCH | Ensure at/cron is restricted to authorized users"
  block:
      - name: "SCORED | 5.1.8 | PATCH | Ensure at/cron is restricted to authorized users"
        file:
            dest: /etc/at.deny
            state: absent

      - name: "SCORED | 5.1.8 | PATCH | Check if at.allow exists"
        stat:
            path: "/etc/at.allow"
        register: at_allow

      - name: "SCORED | 5.1.8 | PATCH | Ensure at/cron is restricted to authorized users"
        file:
            dest: /etc/at.allow
            state: '{{ "file" if  at_allow.stat.exists else "touch" }}'
            owner: root
            group: root
            mode: 0600

      - name: "SCORED | 5.1.8 | PATCH | Ensure at/cron is restricted to authorized users"
        file:
            dest: /etc/cron.deny
            state: absent

      - name: "SCORED | 5.1.8 | PATCH | Check if cron.allow exists"
        stat:
            path: "/etc/cron.allow"
        register: cron_allow

      - name: "SCORED | 5.1.8 | PATCH | Ensure at/cron is restricted to authorized users"
        file:
            dest: /etc/cron.allow
            state: '{{ "file" if  cron_allow.stat.exists else "touch" }}'
            owner: root
            group: root
            mode: 0600
  when:
      - ubuntu1804cis_rule_5_1_8
  tags:
      - level1
      - scored
      - patch
      - cron
      - rule_5.1.8

- name: "SCORED | 5.2.1 | PATCH | Ensure permissions on /etc/ssh/sshd_config are configured"
  file:
      dest: /etc/ssh/sshd_config
      state: file
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu1804cis_rule_5_2_1
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.1

- name: "SCORED | 5.2.2 | PATCH | Ensure SSH Protocol is set to 2"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^Protocol'
      line: 'Protocol 2'
  when:
      - ubuntu1804cis_rule_5_2_2
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.2

- name: "SCORED | 5.2.3 | PATCH | Ensure SSH LogLevel is set to INFO"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^LogLevel'
      line: 'LogLevel INFO'
  when:
      - ubuntu1804cis_rule_5_2_3
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.3

- name: "SCORED | 5.2.4 | PATCH | Ensure SSH X11 forwarding is disabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^X11Forwarding'
      line: 'X11Forwarding no'
  when:
      - ubuntu1804cis_rule_5_2_4
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.4

- name: "SCORED | 5.2.5 | PATCH | Ensure SSH MaxAuthTries is set to 4 or less"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^(#)?MaxAuthTries \d'
      line: 'MaxAuthTries 4'
  when:
      - ubuntu1804cis_rule_5_2_5
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.5

- name: "SCORED | 5.2.6 | PATCH | Ensure SSH IgnoreRhosts is enabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^IgnoreRhosts'
      line: 'IgnoreRhosts yes'
  when:
      - ubuntu1804cis_rule_5_2_6
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.6

- name: "SCORED | 5.2.7 | PATCH | Ensure SSH HostbasedAuthentication is disabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^HostbasedAuthentication'
      line: 'HostbasedAuthentication no'
  when:
      - ubuntu1804cis_rule_5_2_7
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.7

- name: "SCORED | 5.2.8 | PATCH | Ensure SSH root login is disabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin'
      line: 'PermitRootLogin no'
  when:
      - ubuntu1804cis_rule_5_2_8
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.8

- name: "SCORED | 5.2.9 | PATCH | Ensure SSH PermitEmptyPasswords is disabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^PermitEmptyPasswords'
      line: 'PermitEmptyPasswords no'
  when:
      - ubuntu1804cis_rule_5_2_9
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.9

- name: "SCORED | 5.2.10 | PATCH | Ensure SSH PermitUserEnvironment is disabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^PermitUserEnvironment'
      line: 'PermitUserEnvironment no'
  when:
      - ubuntu1804cis_rule_5_2_10
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.10

- name: "SCORED | 5.2.11 | PATCH | Ensure only approved MAC algorithms are used"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^MACs'
      line: 'MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com'
  when:
      - ubuntu1804cis_rule_5_2_11
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.11

- name: "SCORED | 5.2.12 | PATCH | Ensure SSH Idle Timeout Interval is configured"
  block:
      - name: "SCORED | 5.2.12 | PATCH | Ensure SSH Idle Timeout Interval is configured"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: '^ClientAliveInterval'
            line: "ClientAliveInterval {{ ubuntu1804cis_sshd['clientaliveinterval'] }}"

      - name: "SCORED | 5.2.12 | PATCH | Ensure SSH ClientAliveCountMax set to <= 3"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: '^ClientAliveCountMax'
            line: "ClientAliveCountMax {{ ubuntu1804cis_sshd['clientalivecountmax'] }}"
  when:
      - ubuntu1804cis_rule_5_2_12
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.12

- name: "SCORED | 5.2.13 | PATCH | Ensure SSH LoginGraceTime is set to one minute or less"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^LoginGraceTime'
      line: "LoginGraceTime 60"
  when:
      - ubuntu1804cis_rule_5_2_13
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.13

- name: "SCORED | 5.2.14 | PATCH | Ensure SSH access is limited"
  block:
      - name: "SCORED | 5.2.14 | PATCH | Ensure SSH access is limited - allowusers"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: '^AllowUsers'
            line: "AllowUsers {{ ubuntu1804cis_sshd['allowusers'] }}"
        notify:
            - restart sshd
        when:
            - "ubuntu1804cis_sshd['allowusers']|default('')"

      - name: "SCORED | 5.2.14 | PATCH | Ensure SSH access is limited - allowgroups"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: '^AllowGroups'
            line: "AllowGroups {{ ubuntu1804cis_sshd['allowgroups'] }}"
        notify:
            - restart sshd
        when:
            - "ubuntu1804cis_sshd['allowgroups']|default('')"

      - name: "SCORED | 5.2.14 | PATCH | Ensure SSH access is limited - denyusers"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: '^DenyUsers'
            line: "DenyUsers {{ ubuntu1804cis_sshd['denyusers'] }}"
        notify:
            - restart sshd
        when:
            - "ubuntu1804cis_sshd['denyusers']|default('')"

      - name: "SCORED | 5.2.14 | PATCH | Ensure SSH access is limited - denygroups"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: '^DenyGroups'
            line: "DenyGroups {{ ubuntu1804cis_sshd['denygroups'] }}"
        notify:
            - restart sshd
        when:
            - "ubuntu1804cis_sshd['denygroups']|default('')"
  when:
      - ubuntu1804cis_rule_5_2_14
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.14

- name: "SCORED | 5.2.15 | PATCH | Ensure SSH warning banner is configured"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^Banner'
      line: 'Banner /etc/issue.net'
  when:
      - ubuntu1804cis_rule_5_2_15
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.15

- name: "SCORED | 5.3.1 | PATCH | Ensure password creation requirements are configured"
  block:
      - name: "SCORED | 5.3.1 | PATCH | Ensure lipam-pwquality is installed"
        apt:
            name: libpam-pwquality
            state: present
            install_recommends: false

      - name: "SCORED | 5.3.1 | PATCH | Ensure password creation requirements are configured"
        lineinfile:
            state: present
            dest: /etc/security/pwquality.conf
            regexp: '^{{ item.key }}'
            line: '{{ item.key }} = {{ item.value }}'
        with_items:
            - "{{ ubuntu1804cis_pwquality }}"
  when:
      - ubuntu1804cis_rule_5_3_1
  tags:
      - level1
      - scored
      - patch
      - rule_5.3.1

- name: "SCORED | 5.3.2 | PATCH | Ensure lockout for failed password attempts is configured"
  lineinfile:
      dest: /etc/pam.d/common-auth
      line: 'auth required pam_tally2.so onerr=fail audit silent deny=5 unlock_time=900'
  when:
      - ubuntu1804cis_rule_5_3_2
  tags:
      - level1
      - scored
      - patch
      - rule_5.3.2

- name: "SCORED | 5.3.3 | PATCH | Ensure password reuse is limited"
  lineinfile:
      dest: /etc/pam.d/common-password
      line: 'password required pam_pwhistory.so remember=5'
  when:
      - ubuntu1804cis_rule_5_3_3
  tags:
      - level1
      - scored
      - patch
      - rule_5.3.3

- name: "SCORED | 5.3.4 | PATCH | Ensure password hashing algorithm is SHA-512"
  command: authconfig --passalgo=sha512 --update
  changed_when: false
  failed_when: false
  when:
      - ubuntu1804cis_rule_5_3_4
  tags:
      - level1
      - scored
      - patch
      - rule_5.3.4

- name: "SCORED | 5.4.1.1 | PATCH | Ensure password expiration is 365 days or less"
  lineinfile:
      state: present
      dest: /etc/login.defs
      regexp: '^PASS_MAX_DAYS'
      line: "PASS_MAX_DAYS {{ ubuntu1804cis_pass['max_days'] }}"
  when:
      - ubuntu1804cis_rule_5_4_1_1
  tags:
      - level1
      - scored
      - patch
      - rule_5.4.1.1

- name: "SCORED | 5.4.1.2 | PATCH | Ensure minimum days between password changes is 7 or more"
  lineinfile:
      state: present
      dest: /etc/login.defs
      regexp: '^PASS_MIN_DAYS'
      line: "PASS_MIN_DAYS {{ ubuntu1804cis_pass['min_days'] }}"
  when:
      - ubuntu1804cis_rule_5_4_1_2
  tags:
      - level1
      - scored
      - patch
      - rule_5.4.1.2

- name: "SCORED | 5.4.1.3 | PATCH | Ensure password expiration warning days is 7 or more"
  lineinfile:
      state: present
      dest: /etc/login.defs
      regexp: '^PASS_WARN_AGE'
      line: "PASS_WARN_AGE {{ ubuntu1804cis_pass['warn_age'] }}"
  when:
      - ubuntu1804cis_rule_5_4_1_3
  tags:
      - level1
      - scored
      - patch
      - rule_5.4.1.3

- name: "SCORED | 5.4.1.4 | PATCH | Ensure inactive password lock is 30 days or less"
  command: /bin/true
  changed_when: false
  when:
      - ubuntu1804cis_rule_5_4_1_4
  tags:
      - level1
      - scored
      - patch
      - rule_5.4.1.4
      - notimplemented

- name: "SCORED | 5.4.2 | PATCH | Ensure system accounts are non-login"
  command: >
    for user in `awk -F: '($3 < 1000) {print $1 }' /etc/passwd`; do
     if [ $user != "root" ]; then
      usermod -L $user
      if [ $user != "sync" ] && [ $user != "shutdown" ] && [ $user != "halt" ];
      then
        usermod -s /usr/sbin/nologin $user
      fi
     fi
    done
  changed_when: false
  when:
      - ubuntu1804cis_rule_5_4_2
      - system_accounts_non_login_1.stdout
      - system_accounts_non_login_2.stdout
  tags:
      - level1
      - patch
      - rule_5.4.2
      - scored

- name: "SCORED | 5.4.3 | PATCH | Ensure default group for the root account is GID 0"
  command: usermod -g 0 root
  changed_when: false
  failed_when: false
  when:
      - ubuntu1804cis_rule_5_4_3
  tags:
      - level1
      - patch
      - rule_5.4.3
      - scored

- name: "SCORED | 5.4.4 | PATCH | Ensure default user umask is 027 or more restrictive"
  block:

      - name: "SCORED | 5.4.4 | PATCH | Check if bashrc exists"
        stat:
            path: "/etc/bashrc"
        register: bashrc_present

      - name: "SCORED | 5.4.4 | PATCH | Ensure default user umask is 027 or more restrictive - /etc/bashrc"
        replace:
            path: /etc/bashrc
            regexp: '(^\s+umask) 002'
            replace: '\1 027'
        when: bashrc_present.stat.exists

      - name: "SCORED | 5.4.4 | PATCH | Ensure default user umask is 027 or more restrictive - /etc/profile"
        replace:
            path: /etc/profile
            regexp: '(^\s+umask) 002'
            replace: '\1 027'
  when:
      - ubuntu1804cis_rule_5_4_4
  tags:
      - level1
      - patch
      - rule_5.4.4
      - scored

- name: "NOTSCORED | 5.5 | PATCH | Ensure root login is restricted to system console"
  command: /bin/true
  changed_when: false
  when:
      - ubuntu1804cis_rule_5_5
  tags:
      - level1
      - patch
      - rule_5.5
      - notscored
      - notimplemented

- name: "SCORED | 5.6 | PATCH | Ensure access to the su command is restricted"
  lineinfile:
      state: present
      dest: /etc/pam.d/su
      regexp: '^(#)?auth\s+required\s+pam_wheel\.so'
      line: "auth           required        pam_wheel.so use_uid"
  when:
      - ubuntu1804cis_rule_5_6
  tags:
      - level1
      - patch
      - rule_5.6
      - scored

- name: "SCORED | 5.6 | PATCH | Ensure access to the su command is restricted - sudo group contains root"
  user:
      name: root
      groups: sudo
  when:
      - ubuntu1804cis_rule_5_6
  tags:
      - level1
      - patch
      - rule_5.6
      - scored
