---
# handlers file for Ubuntu1804-CIS

- name: sysctl flush ipv4 route table
  become: true
  sysctl:
      name: net.ipv4.route.flush
      value: 1
      sysctl_set: true
  when: ansible_virtualization_type != "docker"

- name: sysctl flush ipv6 route table
  become: true
  sysctl:
      name: net.ipv6.route.flush
      value: 1
      sysctl_set: true
  when: ansible_virtualization_type != "docker"

- name: systemd restart tmp.mount
  become: true
  systemd:
      name: tmp.mount
      daemon_reload: true
      enabled: true
      masked: false
      state: reloaded
  when: ansible_virtualization_type != "docker"
  ignore_errors: "{{ ubuntu1804cis_ignore_remount_errors }}"

- name: systemd restart var-tmp.mount
  become: true
  systemd:
      name: var-tmp.mount
      daemon_reload: true
      enabled: true
      masked: false
      state: reloaded
  ignore_errors: "{{ ubuntu1804cis_ignore_remount_errors }}"

- name: generate new grub config
  become: true
  command: grub-mkconfig -o "{{ grub_cfg.stat.path }}"
  notify: fix permissions after generate new grub config handler

- name: fix permissions after generate new grub config handler
  become: true
  file:
    path: "/boot/grub/grub.cfg"
    owner: root
    group: root
    mode: 0600
  when:
    - ansible_os_family == "Debian"
    - ubuntu1804cis_rule_1_4_1

- name: restart firewalld
  become: true
  service:
      name: firewalld
      state: restarted

- name: restart xinetd
  become: true
  service:
      name: xinetd
      state: restarted

- name: restart sshd
  become: true
  service:
      name: sshd
      state: restarted

- name: reload dconf
  become: true
  command: dconf update

- name: restart auditd
  become: true
  service:
      name: auditd
      state: restarted
  when:
      - not ubuntu1804cis_skip_for_travis
  tags:
      - skip_ansible_lint

- name: load audit rules
  become: true
  command: /sbin/augenrules --load
  when:
      - not ubuntu1804cis_skip_for_travis
  tags:
      - skip_ansible_lint
